### ISSUE TITLE
JDBC URL in Line No 25 is not proper

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#102]
Link : https://github.com/secure-device-onboard/pri-fidoiot/blame/master/demo/reseller/README.md
JDBC URL in Line No 25 can be described as Default value: jdbc:h2:tcp://localhost:8071/./target/data/reseller (or) Default value: jdbc:h2:tcp://localhost:8071/./target/data/<db_name>

**Comment by Darshini-Parikh93** [comment]
Fixed in [PR100](https://github.com/secure-device-onboard/pri-fidoiot/pull/100)
