### ISSUE TITLE
Port Number and Database Name needs modification

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#103]
Link : https://github.com/secure-device-onboard/pri-fidoiot/blame/master/demo/owner/README.md
Line No 41 : Its owner database, its mentioned as RV  database.
Line No 42 : Default value: 8050 whereas in JDBC URL port number is 8051(jdbc:h2:tcp://localhost:8051/./target/data/ops)

**Comment by Darshini-Parikh93** [comment]
Fixed in [PR100](https://github.com/secure-device-onboard/pri-fidoiot/pull/100)
