### ISSUE TITLE
Serviceinfoids word creates ambiguity.

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#104]
Link : https://github.com/secure-device-onboard/pri-fidoiot/blame/master/demo/README.md
Line No 141: Can we mention the table name(OWNER_SERVICEINFO) and corredsponding header names(SVI_ID) instead of serviceinfoids or can it be renamed as serviceinfo ids.

**Comment by trbehera** [comment]
No longer valid after README refactor related to ServiceInfo changes.
