### ISSUE TITLE
Wordings needs minor correction in 3 ReadMes

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#115]
Link:https://github.com/secure-device-onboard/pri-fidoiot/blob/master/demo/manufacturer/README.md Line No 108
Link:https://github.com/secure-device-onboard/pri-fidoiot/blob/master/demo/reseller/README.md Line No 128
Link:https://github.com/secure-device-onboard/pri-fidoiot/blob/master/demo/owner/README.md Line No 167
It has Line "To insert/replace an existing PrivateKeyEntry of any particular algorithm, refer to section Inserting Keys into Keystore. To insert new certificate/private-key pair into <fido-iot-src>/demo/manufacturer/manufacturer_keystore.p12."
can it be replaced to "To insert/replace an existing PrivateKeyEntry of any particular algorithm or To insert new certificate/private-key pair into <fido-iot-src>/demo/manufacturer/manufacturer_keystore.p12, To insert/replace an existing PrivateKeyEntry of any particular algorithm, refer to section Inserting Keys into Keystore. To insert new certificate/private-key pair into <fido-iot-src>/demo/manufacturer/manufacturer_keystore.p12."

**Comment by trbehera** [comment]
Fixed in #237

**Comment by trbehera** [comment]
Fixed in #237
