### ISSUE TITLE
Path for whitelisting the hashes is in different location

### ISSUE THREAD

**Issue by swamyb3679** [secure-device-onboard/pri-fidoiot#192]
https://github.com/secure-device-onboard/pri-fidoiot/blob/master/component-samples/demo/rv/README.md

config.properties file exists in <fido-iot-src>/util/storage-samples/storage-rv-sample/src/main/resources/

But in readme file, it has different path

**Comment by trbehera** [comment]
Fixed in commit e74c21e8
