### ISSUE TITLE
[PRI-Component-Sample] fido.iot.device.cred.reuse value accepts any random values and throws exception

### ISSUE THREAD

**Issue by apatangx** [secure-device-onboard/pri-fidoiot#208]
PRI-Component Sample Device

Commit id: 5f92318c7e0280d2f1d3f959e840882caf29917f

1. Manufacturer, Owner and RV are up and running.

2. RvByPass flag is not set

3. DI and TO0 completed successfully.

4. For TO1 go to the device path: pri-fidoiot/component-samples/demo/device execute following command: 

          java -Dfido.iot.device.cred.reuse= <input>  -jar device.jar

5. Observe the Class not found exception/ Error.

Note: any random value which has space in it (within single quotes or without quotes) throws this exception.

<input for cred.reuse flag>

1) All special characters

2) Paragraph within single quotes

3) Paragraph within double quotes starting with space  (eg: fido.iot.device.cred.reuse= "paragraph contents" -jar device.jar)

4)  01110100 01110010 01110101 01100101

5) 
![DE2563-1](https://user-images.githubusercontent.com/79901799/114079052-51030b80-98c7-11eb-856f-54fec88f1df2.PNG)
![DE2563-2](https://user-images.githubusercontent.com/79901799/114079055-52cccf00-98c7-11eb-8c54-a95896a311b1.PNG)
![DE2563-3](https://user-images.githubusercontent.com/79901799/114079056-53656580-98c7-11eb-9f13-f4c755b2f346.PNG)
![DE2563-4](https://user-images.githubusercontent.com/79901799/114079060-54969280-98c7-11eb-9e55-fcde1b4f110b.PNG)
![DE2563-5](https://user-images.githubusercontent.com/79901799/114079061-552f2900-98c7-11eb-9c69-d8eca645462e.PNG)
![DE2563-6](https://user-images.githubusercontent.com/79901799/114079065-55c7bf80-98c7-11eb-893d-2bef216a687a.PNG)
![DE2563-7](https://user-images.githubusercontent.com/79901799/114079067-56605600-98c7-11eb-888f-53c3036db200.PNG)
![DE2563-8](https://user-images.githubusercontent.com/79901799/114079068-56605600-98c7-11eb-88cf-5645874cbf51.PNG)
![DE2563-9](https://user-images.githubusercontent.com/79901799/114079073-56f8ec80-98c7-11eb-8803-04b4005f6fac.PNG)

'01110100 01110010 01110101 01100101'

6) 00/

**Comment by DukeDavis12** [comment]
1. Java compiler expects java applications to pass parameters without any space in between the key and value. In this specific case `java -Dfidoalliance.cred.reuse= <param-value> -jar device.jar` ; java compiler sets the cred.reuse value to null and searches for <param-value> class to compile; thus returning ClassNotFoundException.

2. As this error is seen even before entering the application; It is out of scope for us to implement a fix for it.

3. Workaround for this issue would be updating the _JDK_OPTIONS to the format of your preference.
