### ISSUE TITLE
Device starting commands to be run through "java -jar" instead of "mvn exec:java"

### ISSUE THREAD

**Issue by swamyb3679** [secure-device-onboard/pri-fidoiot#220]
In the device readme <https://github.com/secure-device-onboard/pri-fidoiot/blob/master/component-samples/demo/device/README.md>, observed the following command.

**Observed**: mvn -Dfidoalliance.fdo.url.di=<di-server-URL> -Dfidoalliance.fdo.pem.dev=<device-PEM-file> exec:java
**Expected**: java -jar -Dfidoalliance.fdo.url.di=<di-server-URL> -Dfidoalliance.fdo.pem.dev=<device-PEM-file> device.jar

**Comment by trbehera** [comment]
Fixed in #237

**Comment by trbehera** [comment]
Fixed in #237
