### ISSUE TITLE
Links to demo components samples and On Die ReadMe are not functional

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#230]
Links to demo components samples and On Die ReadMe are not functional.
Gives page not found error.
Line No:198, 202

**Comment by trbehera** [comment]
Please mention the filename where this issue exists.

**Comment by trbehera** [comment]
Fixed in #237

**Comment by trbehera** [comment]
Fixed in #237
