### ISSUE TITLE
PRIFIDO-IOT/README Issues

### ISSUE THREAD

**Issue by DukeDavis12** [secure-device-onboard/pri-fidoiot#231]
PRI-fidoiot/README.md

[line 22] prelimnary --> preliminary (Wrong Spelling)
[line 22] enduser --> end user 
[line 24] Sentence closing with `..`
[line 26]  cert-utils - loading -->  cert-utils - for loading 
[line 31] which follow describe a simple (Wrong structuring)
[line 86-90] Add a line like ` Expect the following message on successful DI completion` + 3 lines rendered in a single line.
[line 97-101] Add a line like ` Expect the following message on successful TO0 completion` + 2 lines rendered in a single line.
[line 119] Protcol --> Protocol (Wrong Spelling)
[line 119] discrepency --> discrepancy (Wrong Spelling)
[line 119] maven --> Maven
[line 137] NOTE --> not in a new line.
[line 147] out in following --> out in the following
[line 178] a FDO --> an FDO.
[line 198] link not working.
[line 202] link not working.

**Comment by trbehera** [comment]
Fixed in #237

**Comment by trbehera** [comment]
Fixed in #237
