### ISSUE TITLE
PRI-fidoiot/component-samples/demo README issues

### ISSUE THREAD

**Issue by DukeDavis12** [secure-device-onboard/pri-fidoiot#232]
[Line 88] entries the the --> entries the 
[Line 90] downloaded direct from  --> downloaded directly from 
[Line 92] In such cases it is recommended --> In such cases, it is recommended.
[Line 99] URL containing of the zip file --> URL containing the zip file
[Line 146]  with value --> with the value
[Line 150] setupinfo -->setup info
[Line 164] Sample serviceInfo in old format ('fdo_sys:filedesc=filename, fdo_sys:write=filecontent,fdo_sys:exec=command-to-execute')
[Line 168]  preceeding --> preceding (Wrong Spelling)
[Line 174] that are sent --> that is sent

**Comment by trbehera** [comment]
Fixed in #237

**Comment by trbehera** [comment]
Fixed in #237
