### ISSUE TITLE
demo/rv README Issues

### ISSUE THREAD

**Issue by DukeDavis12** [secure-device-onboard/pri-fidoiot#233]
[Line 6-7] Docker Engine & Docker-compose missing
[Line 84,91,98] NOTE is not rendered on a new line.
[Line 143] hash need to be --> hash needs to be

**Comment by trbehera** [comment]
Fixed in #237

**Comment by trbehera** [comment]
Fixed in #237

**Comment by trbehera** [comment]
Fixed in #237
