### ISSUE TITLE
Remove printStackTrace() statements

### ISSUE THREAD

**Issue by trbehera** [secure-device-onboard/pri-fidoiot#24]
printStackTrace() messages should be replaced with SOP statements till a logger is implemented.

_Originally posted by @trbehera in https://github.com/secure-device-onboard/pri-fidoiot/pull/17#discussion_r510299366_

**Comment by Darshini-Parikh93** [comment]
All printStackTrace() messages removed in [PR#80](https://github.com/secure-device-onboard/pri-fidoiot/commit/7d67295f1738c487da0fab070757c222035d3b2e)
