### ISSUE TITLE
[Demo/RV] Update README file.

### ISSUE THREAD

**Issue by trbehera** [secure-device-onboard/pri-fidoiot#37]
Update README file.

_Originally posted by @trbehera in https://github.com/secure-device-onboard/pri-fidoiot/pull/34#r520266348_

**Comment by Darshini-Parikh93** [comment]
Updated in [PR#72](https://github.com/secure-device-onboard/pri-fidoiot/commit/730fb7975fbc5b5f34dcd510086dd2f1f626c77b)
