### ISSUE TITLE
Modify the File path of http-server-samples, http-client-samples to protocol-samples in ReadMe

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#44]
ReadMe Link : https://github.com/secure-device-onboard/pri-fidoiot/blame/master/README.md
Modify http-server-samples to folder name protocol-samples in Line No 45,54,63,97.
Modify http-client-samples to folder name protocol-samples in Line No 75,107,116,125.

**Comment by Darshini-Parikh93** [comment]
Updated in [PR#59](https://github.com/secure-device-onboard/pri-fidoiot/commit/8f19facb6a29ba16ea076ea98c193b387b9e221d)
