### ISSUE TITLE
Folder mismatch observed in ReadMe with respect to the downloaded code

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#45]
ReadMe Url: https://github.com/secure-device-onboard/pri-fidoiot/blame/master/README.md
Folder Name in ReadMe is http-server-rv-sample(Line No:45) ,  http-server-owner-sample(Line No:54) whereas actual folder name is http-server-to0-to1-sample , http-server-to2-sample respectively.

**Comment by Darshini-Parikh93** [comment]
Fixed in [PR#59](https://github.com/secure-device-onboard/pri-fidoiot/commit/8f19facb6a29ba16ea076ea98c193b387b9e221d)
