### ISSUE TITLE
[BUG] Document Content Error

### ISSUE THREAD

**Issue by nccu-ben** [secure-device-onboard/pri-fidoiot#580]
**Describe the bug**
Content error at  the document : component-samples/demo/device/README.md

**To Reproduce**
In the document : component-samples/demo/device/README.md
      Instruction says: 
      $ cd <fdo-pri-src>/component-samples/http-device-sample/
      But it should be:
      $ cd <fdo-pri-src>/component-samples/device/

**Expected behavior**
Wrong Content

**Screenshots**
<img width="1348" alt="截圖 2023-03-07 上午1 40 31" src="https://user-images.githubusercontent.com/48372928/223188461-e6d13fef-9733-47ad-a61f-5a9ec1548d7f.png">

**Test Environment**
Provide details about your test environment.

**Additional context**

**Comment by DukeDavis12** [comment]
Great catch @nccu-ben. Can you share a PR with the changes?

**Comment by nccu-ben** [comment]
Hi @DukeDavis12 , here is the PR.
[https://github.com/secure-device-onboard/pri-fidoiot/pull/578](url)
If you could look it over, it'll be my honor.
