### ISSUE TITLE
Modify http-server-samples to protocol-samples

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#75]
Link: https://github.com/secure-device-onboard/pri-fidoiot/blame/master/README.md
Line No 130: Modify http-server-samples to protocol-samples

**Comment by Darshini-Parikh93** [comment]
Fixed in [PR#59](https://github.com/secure-device-onboard/pri-fidoiot/commit/8f19facb6a29ba16ea076ea98c193b387b9e221d) and [PR#72](https://github.com/secure-device-onboard/pri-fidoiot/commit/730fb7975fbc5b5f34dcd510086dd2f1f626c77b)
