### ISSUE TITLE
README Link is not added and other links are not functional

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#76]
Link: https://github.com/secure-device-onboard/pri-fidoiot/blame/master/README.md
Line No 214, 313, 390,500:Can ReadMe link can be added.
Line No 375,437 : Link(https://verify.epid-sbx.trustedservices.intel.com) is not working
Line No 376,438 : Link(https://verify.epid.trustedservices.intel.com/) is not working.
Line No 376,438: Link (https://localhost:1180) is not working.

**Comment by Darshini-Parikh93** [comment]
https://verify.epid-sbx.trustedservices.intel.com, https://verify.epid.trustedservices.intel.com/ are the URL for the hosted verification service. If you want to check if the service is up and running you need to run the healthcheck API, simply clicking on the url is not enough.
Healthcheck API for verification service: http://verify.epid-sbx.trustedservices.intel.com/health, http://verify.epid.trustedservices.intel.com/health respectively.
For the localhost URL to work the onprem verification service should be running and appropriate healthcheck API should be run to see the service status. Read the README files includes in the RV onprem package for more info.

**Comment by Darshini-Parikh93** [comment]
Updated in [PR#72](https://github.com/secure-device-onboard/pri-fidoiot/commit/730fb7975fbc5b5f34dcd510086dd2f1f626c77b)
