### ISSUE TITLE
Path can be a typo

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#77]
Link: https://github.com/secure-device-onboard/pri-fidoiot/blame/master/README.md
•	Line No 147 , 148 : has path which could be a typo “Copy /demo//java.security to /etc/java-11-openjdk/security/” and “Copy /demo//pkcs11.cfg to /etc/softhsm/”

**Comment by Darshini-Parikh93** [comment]
Resolved in [PR#72](https://github.com/secure-device-onboard/pri-fidoiot/pull/72)
