### ISSUE TITLE
Path mismatch is observed 

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#79]
Link: https://github.com/secure-device-onboard/pri-fidoiot/blame/master/README.md
Line No 552 and 558: We need to run device DI from  demo/device whereas in Line No 552 its from Device and its 558 from demo/device.

**Comment by Darshini-Parikh93** [comment]
Resolved in [PR#72](https://github.com/secure-device-onboard/pri-fidoiot/pull/72)
