### ISSUE TITLE
Path Mismatch is observed in Line 79

### ISSUE THREAD

**Issue by SSWAMIN1SSS** [secure-device-onboard/pri-fidoiot#97]
Link : https://github.com/secure-device-onboard/pri-fidoiot/blame/master/demo/rv/README.md
Line No 79: Path of config.properties is "<fido-iot-src>/storage/storage-samples/storage-rv-sample/src/main/resources" whereas path mentioned in readme is "<fido-iot-src>/storage/storage-rv-sample/src/main/resources"

**Comment by Darshini-Parikh93** [comment]
Fixed in [PR100](https://github.com/secure-device-onboard/pri-fidoiot/pull/100)
